rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  requiredStatusCheckContexts:
    - 'Kokoro CI'
    - 'cla/google'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: yoshi
    permission: push
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java
    permission: push
  - team: yoshi-nodejs
    permission: push
  - team: yoshi-php
    permission: push
  - team: yoshi-python
    permission: push
  - team: yoshi-ruby
    permission: push
