steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
      '-t', 'gcr.io/$PROJECT_ID/owlbot-java:$SHORT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/owlbot-java:latest',
      '-f', 'docker/owlbot/java/Dockerfile', '.' ]

  - name: gcr.io/gcp-runtimes/structure_test
    args:
      ["-i", "gcr.io/$PROJECT_ID/owlbot-java:$SHORT_SHA", "--config", "docker/owlbot/java/cloudbuild_test.yaml", "-v"]

images:
  - gcr.io/$PROJECT_ID/owlbot-java:$SHORT_SHA
  - gcr.io/$PROJECT_ID/owlbot-java:latest
